# This is the original rule we want to work
[[headers]]
  for = "/assetlinks.json" # <-- REMOVED .well-known
  [headers.values]
    Content-Type = "application/json"

# This is a new rule for testing purposes
[[headers]]
  for = "/index.html"
  [headers.values]
    X-Test-Header = "Hello from Netlify!"